# vim: set ft=yaml ts=2 expandtab:

# This file is part of ansible-collection-scl
# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
#
# ansible-collection-scl is free software: you can redistribute it 
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# ansible-collection-scl is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ansible-collection-scl.
# If not, see <https://www.gnu.org/licenses/>.

---

- name: converge scl
  hosts: all,!infrastructure_group

  environment:
    http_proxy: http://ci-proxy:3128
    https_proxy: http://ci-proxy:3128

  tasks:

  - block:

    - name: include mafalb.epel.release
      ansible.builtin.include_role:
        name: mafalb.scl.rh

    rescue:
      
    - name: it is ok that non EL7 fails
      ansible.builtin.assert:
        that:
        - ansible_distribution_major_version is version('7', '>')
      when: ansible_os_family == 'RedHat'

    - name: it is ok that non EL fails
      ansible.builtin.assert:
        that:
        - ansible_os_family != 'RedHat'
      when: ansible_os_family != 'RedHat'

...
