# vim: set ft=yaml ts=2 expandtab:

# This file is part of ansible-collection-scl
# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
#
# ansible-collection-scl is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# ansible-collection-scl is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ansible-collection-scl.
# If not, see <https://www.gnu.org/licenses/>.

---

dependency:
  name: galaxy
  options:
    role-file: idontexist.yml   # avoid warning while running molecule
    requirements-file: molecule/default/requirements.yml

driver:

  name: docker


lint: |
  set -e
  bash tests/lint.sh

platforms:
- name: ${CI_HOSTNAME-"ci-rocky8"}
  image: ${CI_IMAGE:-"quay.io/rockylinux/rockylinux:8"}
  command: /lib/systemd/systemd
  network_mode: bridge
  docker_networks:
  - name: molecule-internal
    internal: true
  networks:
  - name: molecule-internal
  volumes:
  - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  tmpfs:
  - /tmp
  - /run
  - /run/lock
  capabilities:
  - SYS_ADMIN
  privileged: ${CI_CONTAINER_PRIVILEGED:-false}
  pre_build_image: ${CI_CONTAINER_PREBUILT:-false}
  tty: true
  groups:
  - ci

- name: ci-proxy
  image: quay.io/rockylinux/rockylinux:8
  command: /lib/systemd/systemd
  network_mode: bridge
  networks:
  - name: molecule-external
  - name: molecule-internal
  volumes:
  - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  tmpfs:
  - /tmp
  - /run
  - /run/lock
  capabilities:
  - SYS_ADMIN
  privileged: ${CI_CONTAINER_PRIVILEGED:-false}
  pre_build_image: ${CI_CONTAINER_PREBUILT:-false}
  tty: true
  groups:
  - infrastructure_group
  - proxy_group

provisioner:
  name: ansible
  ansible_args:
    - --tags=all,debug
    - --diff
  config_options:
    defaults:
      gathering: smart
      interpreter_python: auto
  lint:
    name: ansible-lint

verifier:
  name: ansible
  lint:
    name: ansible-lint

...
