# vim: set ft=yaml ts=2 expandtab:
---

- name: assert that OS is supported
  assert:
    that:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == '7'

- name: include OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
  - "{{ ansible_distribution }}.yml"

- name: yum repo for SCL is present
  package:
    name: "{{ rhscl_package }}"

...
